name: Build package

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x', '23.x']
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'pnpm'
    - name: Clean pnpm store
      run: |
        pnpm store prune
        rm -rf node_modules
        rm -rf .pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Run tests & coverage
      run: pnpm run coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: bitsnaps/puter-sdk      